### ISSUE TITLE
Would it be possible to add the resource from Stellaris Evolved?

### ISSUE THREAD

**Issue by adriangaro** [OldEnt/stellaris-universal-resource-patch-ce#3]
Atm we have a manually created resource display for the resource `sr_tec_ai_power` to be mostly compatible with other mods and URP.
Would it be possible to be added to the strategics/other resources area?

Never managed to ask the initial author, but i guess now is as good as any time.

**Comment by OldEnt** [comment]
Done, thanks for reporting!
